### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by slifszyc** [DemocraciaEnRed/cambioclimatico#3]
Upload to a public place and set LOGO config variable to the URL

![los verdes](https://cloud.githubusercontent.com/assets/1213542/9415303/b2e532a6-4814-11e5-8d5c-d5d8e57f9d74.jpg)

**Comment by mjlescano** [comment]
__PNG with transparent BG__
![logo-los-verdes](https://cloud.githubusercontent.com/assets/558901/9417091/fae7a812-481f-11e5-97ea-4c4e30134d3f.png)
